[project]
name = "prompthub-sc"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.counter]
# path = "contracts/counter.clar"
# epoch = "latest"

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = true, trusted_caller = true, callee_filter = false }

[contracts.nft-trait]
path = "contracts/nft-trait.clar"
clarity_version = 2
epoch = "2.5"

[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"
clarity_version = 2
epoch = "2.5"

[contracts.sbtc-token]
path = "contracts/sbtc-token.clar"
clarity_version = 2
epoch = "2.5"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.prompthub-treasury]
path = "contracts/prompthub-treasury.clar"
clarity_version = 2
epoch = "2.5"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.prompthub-marketplace]
path = "contracts/prompthub-marketplace.clar"
clarity_version = 2
epoch = "2.5"
depends_on = ["sip-010-trait-ft-standard", "prompthub-treasury"]

[contracts.prompthub-contests]
path = "contracts/prompthub-contests.clar"
clarity_version = 2
epoch = "2.5"
depends_on = ["sip-010-trait-ft-standard", "prompthub-treasury"]

[contracts.prompthub-escrow-hire]
path = "contracts/prompthub-escrow-hire.clar"
clarity_version = 2
epoch = "2.5"
depends_on = ["sip-010-trait-ft-standard", "prompthub-treasury"]
